syntax = "proto3";
package dream11.od.dto.v1;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

option java_multiple_files = true;
option java_package = "com.dream11.odin.dto.v1";

message Component {
    string name = 1;
    string version = 2;
    string type = 3;
    string status = 4;
    google.protobuf.Struct config = 5;
    google.protobuf.Timestamp created_at = 6;
    google.protobuf.Timestamp updated_at = 7;
    string created_by = 8;
    string updated_by = 9;
}
