syntax = "proto3";
package dream11.od.dto.v1;

import "dream11/oam/provideraccount/v1/provider_account.proto";
import "dream11/od/dto/v1/service.proto";
import "google/protobuf/timestamp.proto";

option java_multiple_files = true;
option java_package = "com.dream11.odin.dto.v1";

message Environment {
    optional int64 id = 1;
    google.protobuf.Timestamp created_at = 2;
    google.protobuf.Timestamp updated_at = 3;
    string created_by = 4;
    optional int64 org_id = 5;
    string name = 6;
    string status = 7;
    repeated dream11.od.dto.v1.Service services = 8;
    repeated AccountInformation account_information = 9;
    string updated_by = 10;
}

message AccountInformation {
  string provider_account_name = 1;
  dream11.oam.provideraccount.v1.GetProviderAccountResponse service_accounts_snapshot = 2;
  string status = 3;
}

message EnvironmentSummary {
  string name = 1;
  string account = 2;
  string state = 3;
  optional string created_by = 5;
}
