authConfig = {
  jwtConfig = {
    privateKey = ${ODIN_PRIVATE_KEY}
    publicKey =  ${ODIN_PUBLIC_KEY}
  }
}

odinAccountManagerConfig = {
  host = ${?ODIN_ACCOUNT_MANAGER_HOST}
  port = ${?ODIN_ACCOUNT_MANAGER_PORT}
  channel = ${?ODIN_ACCOUNT_MANAGER_CHANNEL}
}

mysql = {
  master = {
    connectOptions = {
      host = ${?ODIN_MYSQL_MASTER_HOST}
      user = ${?ODIN_MYSQL_USERNAME}
      password = ${?ODIN_MYSQL_PASSWORD}
    }
  }
  slave = {
    connectOptions = {
      host = ${?ODIN_MYSQL_SLAVE_HOST}
      user = ${?ODIN_MYSQL_USERNAME}
      password = ${?ODIN_MYSQL_PASSWORD}
    }
  }
}

queue = {
  request = {
    endpoint = ${?ODIN_QUEUE_REQUEST_ENDPOINT}
    queueUrl = ${?ODIN_QUEUE_REQUEST_URL}
    queueProvider = ${?ODIN_QUEUE_REQUEST_PROVIDER}
    region = ${?ODIN_QUEUE_REQUEST_REGION}
  }
  response = {
    endpoint = ${?ODIN_QUEUE_RESPONSE_ENDPOINT}
    queueUrl = ${?ODIN_QUEUE_RESPONSE_URL}
    queueProvider = ${?ODIN_QUEUE_RESPONSE_PROVIDER}
    region = ${?ODIN_QUEUE_RESPONSE_REGION}
  }
}

interceptors = {
  component = ${?ODIN_INTERCEPTOR_COMPONENT_URLS}
  config = {
    timeout = ${?ODIN_INTERCEPTOR_TIMEOUT_SECONDS}
    retryCount = ${?ODIN_INTERCEPTOR_RETRY_COUNT}
  }
}

logStoreConfig {
  host = ${?ODIN_LOGSTORE_HOST}
  port = ${?ODIN_LOGSTORE_PORT}
  enableSSL = ${?ODIN_LOGSTORE_ENABLE_SSL}
  username = ${?ODIN_LOGSTORE_USERNAME}
  password = ${?ODIN_LOGSTORE_PASSWORD}
  pollingFrequencySeconds = ${?ODIN_LOGSTORE_POLLING_FREQUENCY_SECONDS}
  batchSize = ${?ODIN_LOGSTORE_BATCH_SIZE}
  retryCount = ${?ODIN_LOGSTORE_RETRY_COUNT}
  retryIntervalSeconds = ${?ODIN_LOGSTORE_RETRY_INTERVAL_SECONDS}
}
