authConfig = {
  jwtConfig = {
    expirationMillis = 360000000
  }
}

odinAccountManagerConfig = {
  host = localhost
  port = 80
  channel = PLAINTEXT
}

envDbStatusCheckIntervalSecs = 5
serviceDbStatusCheckIntervalSecs = 5

logStoreConfig {
  host = "vpc-odin-logserver-3gzdjqg5qigvzasm3ajqjcinkq.us-east-1.es.amazonaws.com"
  port = 443
  enableSSL = true
  username = "odin-master"
  password = "SuperSecure_123"
  pollingFrequencySeconds = 2
  batchSize = 50
  retryCount = 30
  retryIntervalSeconds = 2
}

mysql = {
  master = {
    connectOptions = {
      host = localhost
      database = odin_deployer
      user = root
      password = ""
      idleTimeout = 300
      queryTimeout = 180000
    }
    poolOptions = {
      maxSize = 20
    }
  }
  slave = {
    connectOptions = {
      host = localhost
      database = odin_deployer
      user = root
      password = ""
      idleTimeout = 300
      queryTimeout = 180000
    }
    poolOptions = {
      maxSize = 20
    }
  }
}

webclient = {
  idleTimeout = 60
  maxPoolSize = 32
  logActivity = false
  keepAliveTimeout = 6
  tcpKeepAlive = true
  http2KeepAliveTimeout = 6
  useAlpn = true
}

queue = {
  request = {
    queueProvider = "sqs"
    region = "us-east-1"
  }
  response = {
    queueProvider = "sqs"
    region = "us-east-1"
    receiveConfig = {
      maxMessages = 5
    }
  }
}

interceptors = {
  component = []
  config = {
    timeout = 3
    retryCount = 2
  }
}
