masterHost = ${mysql.master.connectOptions.host}
port = ${mysql.master.connectOptions.port}
username = ${mysql.master.connectOptions.user}
password = ${mysql.master.connectOptions.password}
database = ${mysql.master.connectOptions.database}
