
/*******************************
  Auto-generated by migrations:dump goal. DO NOT modify.
********************************/


--
-- start dump : environment_service_component
--

CREATE TABLE `environment_service_component` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `environment_service_id` bigint NOT NULL,
  `action` varchar(50) NOT NULL,
  `name` varchar(256) NOT NULL,
  `status` varchar(20) NOT NULL,
  `config` json NOT NULL,
  `account_data` json DEFAULT NULL,
  `created_by` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(50) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `environment_service_id` (`environment_service_id`,`name`),
  KEY `name` (`name`),
  KEY `service_component_idx` (`environment_service_id`,`name`),
  CONSTRAINT `environment_service_component_ibfk_1` FOREIGN KEY (`environment_service_id`) REFERENCES `environment_service` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- end dump : environment_service_component
--



--
-- start dump : environment_lock
--

CREATE TABLE `environment_lock` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `environment_id` bigint NOT NULL,
  `shared_count` int NOT NULL DEFAULT '0',
  `exclusive` tinyint(1) NOT NULL DEFAULT '0',
  `created_by` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(50) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_env_lock` (`environment_id`),
  CONSTRAINT `environment_lock_ibfk_1` FOREIGN KEY (`environment_id`) REFERENCES `environment` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- end dump : environment_lock
--



--
-- start dump : execution_tasks
--

CREATE TABLE `execution_tasks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `action` varchar(50) NOT NULL,
  `org_id` bigint NOT NULL,
  `response` json NOT NULL DEFAULT (json_object()),
  `status` varchar(20) NOT NULL,
  `entity` varchar(20) NOT NULL,
  `execution_id` varchar(255) NOT NULL DEFAULT '',
  `payload` json NOT NULL DEFAULT (json_object()),
  `created_by` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(50) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- end dump : execution_tasks
--



--
-- start dump : environment
--

CREATE TABLE `environment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `org_id` bigint NOT NULL,
  `name` varchar(256) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(50) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `org_id` (`org_id`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- end dump : environment
--



--
-- start dump : environment_account
--

CREATE TABLE `environment_account` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `environment_id` bigint NOT NULL,
  `status` varchar(20) NOT NULL,
  `action` varchar(50) NOT NULL,
  `accounts_data` json DEFAULT NULL,
  `account_data` json DEFAULT NULL,
  `account_name` varchar(50) NOT NULL,
  `created_by` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(50) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `environment_id` (`environment_id`),
  CONSTRAINT `environment_account_ibfk_1` FOREIGN KEY (`environment_id`) REFERENCES `environment` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- end dump : environment_account
--



--
-- start dump : environment_service_component_lock
--

CREATE TABLE `environment_service_component_lock` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `env_id` bigint NOT NULL,
  `environment_service_id` bigint NOT NULL,
  `environment_service_component_id` bigint NOT NULL,
  `shared_count` int NOT NULL DEFAULT '0',
  `exclusive` tinyint(1) NOT NULL DEFAULT '0',
  `created_by` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(50) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_env_service_component_lock` (`env_id`,`environment_service_id`,`environment_service_component_id`),
  KEY `environment_service_id` (`environment_service_id`),
  KEY `environment_service_component_id` (`environment_service_component_id`),
  CONSTRAINT `environment_service_component_lock_ibfk_1` FOREIGN KEY (`env_id`) REFERENCES `environment` (`id`),
  CONSTRAINT `environment_service_component_lock_ibfk_2` FOREIGN KEY (`environment_service_id`) REFERENCES `environment_service` (`id`),
  CONSTRAINT `environment_service_component_lock_ibfk_3` FOREIGN KEY (`environment_service_component_id`) REFERENCES `environment_service_component` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- end dump : environment_service_component_lock
--



--
-- start dump : action
--

CREATE TABLE `action` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `created_by` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(50) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `actions_name_uindex` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- end dump : action
--



--
-- start dump : environment_service_lock
--

CREATE TABLE `environment_service_lock` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `environment_id` bigint NOT NULL,
  `environment_service_id` bigint NOT NULL,
  `shared_count` int NOT NULL DEFAULT '0',
  `exclusive` tinyint(1) NOT NULL DEFAULT '0',
  `created_by` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(50) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_env_service_lock` (`environment_id`,`environment_service_id`),
  KEY `environment_service_id` (`environment_service_id`),
  CONSTRAINT `environment_service_lock_ibfk_1` FOREIGN KEY (`environment_id`) REFERENCES `environment` (`id`),
  CONSTRAINT `environment_service_lock_ibfk_2` FOREIGN KEY (`environment_service_id`) REFERENCES `environment_service` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- end dump : environment_service_lock
--



--
-- start dump : auth_provider
--

CREATE TABLE `auth_provider` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `org_id` bigint NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type` varchar(50) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `provider_details` json NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `org_id` (`org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- end dump : auth_provider
--



--
-- start dump : environment_service
--

CREATE TABLE `environment_service` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `action` varchar(50) NOT NULL,
  `config` json NOT NULL,
  `environment_id` bigint NOT NULL,
  `name` varchar(256) NOT NULL,
  `status` varchar(50) NOT NULL,
  `created_by` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(50) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_env_name` (`environment_id`,`name`),
  KEY `environment_id` (`environment_id`,`status`),
  CONSTRAINT `environment_service_ibfk_1` FOREIGN KEY (`environment_id`) REFERENCES `environment` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- end dump : environment_service
--


